# Generated by Django 5.0.7 on 2025-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('message', models.TextField()),
                ('lead_stage', models.CharField(default='cold', max_length=20)),
                ('emotion', models.CharField(default='neutral', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
